### ISSUE TITLE
Unable to start OpenMRS. Error thrown was: '/var/lib/OpenMRS' should be a directory but it is not

### ISSUE THREAD

**Issue by rcrichton** [chaityabshah/openmrs-core-docker#1]
Hi, when I tried to run the docker image I got the following. Any ideas?

```
WARN - OpenmrsUtil.getDirectoryInApplicationDataDirectory(1284) |2015-02-16 11:36:54,439| '/var/lib/OpenMRS' doesn't exist.  Creating directories now.
Exception in thread "Thread-4" org.openmrs.module.ModuleException: Unable to start OpenMRS. Error thrown was: '/var/lib/OpenMRS' should be a directory but it is not
    at org.openmrs.web.WebDaemon.startOpenmrs(WebDaemon.java:68)
    at org.openmrs.web.filter.initialization.InitializationFilter$InitializationCompletion$1.run(InitializationFilter.java:1637)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.openmrs.api.APIException: '/var/lib/OpenMRS' should be a directory but it is not
    at org.openmrs.util.OpenmrsUtil.getDirectoryInApplicationDataDirectory(OpenmrsUtil.java:1289)
    at org.openmrs.util.OpenmrsUtil.getOpenmrsLogLocation(OpenmrsUtil.java:1246)
    at org.openmrs.util.OpenmrsUtil.setupLogAppenders(OpenmrsUtil.java:594)
    at org.openmrs.util.OpenmrsUtil.startup(OpenmrsUtil.java:547)
    at org.openmrs.api.context.Context.startup(Context.java:831)
    at org.openmrs.web.Listener.startOpenmrs(Listener.java:195)
    at org.openmrs.web.WebDaemon$1.run(WebDaemon.java:46)
```

**Comment by chaityabshah** [comment]
I was able to reproduce your error but it had no effect on OpenMRS starting up. Go to the url http://192.168.59.103:8080/openmrs/ and you should see your application running.

**Comment by chaityabshah** [comment]
Please let me know if your problem still exists or not so I can close the issue.

**Comment by rcrichton** [comment]
Ah ok, I see. If I navigate to the web app all appears to be working.
